# .github/workflows/sync-upstream-release.yml

name: Sync Upstream Release and Build

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  sync_and_build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }} # Ensure this secret exists in your fork

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        # Use the URL without .git for HTTPS
        run: git remote add upstream https://github.com/JellyLabScripts/FarmHelper

      # --- Fetch Upstream Tags (Corrected Command) ---
      # This step now fetches TAGS instead of just the master branch
      # Verbose flags are kept temporarily for debugging if it fails again
      - name: Fetch Upstream Tags
        env:
          GIT_TRACE: 1
          GIT_TRACE_PACKET: 1
          GIT_TRACE_PERFORMANCE: 1
          GIT_CURL_VERBOSE: 1
          NO_PROXY: '*'
        run: |
          echo "================== GIT CONFIG BEFORE FETCH =================="
          git config --list --show-origin
          echo "================== STARTING FETCH (TAGS) =================="
          # --- THIS IS THE CRUCIAL LINE - Fetching --tags ---
          git fetch upstream --tags -v --progress
          echo "================== FETCH COMMAND EXIT CODE: $? =================="
          # Ensure the command succeeded before proceeding
          if [ $? -ne 0 ]; then
            echo "!! Fetch command failed with non-zero exit code !!"
            exit 1
          fi

      # --- Subsequent Steps ---

      - name: Install GitHub CLI
        uses: github/hub@v2.14.2 # Installs 'hub', which bundles 'gh' CLI

      - name: Install jq (JSON Processor)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Latest Upstream Release Info
        id: upstream_release
        env:
          GH_TOKEN: ${{ github.token }}
          UPSTREAM_REPO: JellyLabScripts/FarmHelper
        run: |
          echo "Fetching latest release tag from $UPSTREAM_REPO..."
          latest_release_tag_json=$(gh release list --repo $UPSTREAM_REPO --limit 1 --json tagName)

          if [[ -z "$latest_release_tag_json" || "$latest_release_tag_json" == "[]" ]]; then
            echo "No releases found on upstream repository $UPSTREAM_REPO."
            echo "No new release found. Exiting cleanly."
            exit 0 # Exit successfully
          fi

          tag_name=$(echo "$latest_release_tag_json" | jq -r '.[0].tagName')

          if [[ -z "$tag_name" || "$tag_name" == "null" ]]; then
            echo "Could not extract tag name from the latest release listing."
            exit 1 # Exit with error
          fi

          echo "Latest upstream tag found: $tag_name"
          echo "Fetching details for tag $tag_name..."

          release_details_json=$(gh release view "$tag_name" --repo $UPSTREAM_REPO --json tagName,isPrerelease,name,body)

          if [[ -z "$release_details_json" ]]; then
             echo "Could not fetch details for release tag $tag_name."
             exit 1 # Exit with error
          fi

          echo "Full release details: $release_details_json"
          fetched_tag_name=$(echo "$release_details_json" | jq -r '.tagName')
          is_prerelease=$(echo "$release_details_json" | jq -r '.isPrerelease')
          release_name=$(echo "$release_details_json" | jq -r '.name')
          release_body=$(echo "$release_details_json" | jq -r '.body')

          if [[ -z "$fetched_tag_name" || "$fetched_tag_name" == "null" ]]; then
             echo "Could not extract details from release view for tag $tag_name."
             exit 1
          fi

          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "is_prerelease=$is_prerelease" >> $GITHUB_OUTPUT
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$release_body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check if Release Exists in Fork for this Tag
        id: check_fork_release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          FORK_REPO: ${{ github.repository }}
          TAG_NAME: ${{ steps.upstream_release.outputs.tag_name }}
        run: |
          echo "Checking for existing release with tag '$TAG_NAME' in fork repository '$FORK_REPO'..."
          if gh release view "$TAG_NAME" --repo "$FORK_REPO" > /dev/null 2>&1; then
            echo "Release with tag '$TAG_NAME' already exists in the fork '$FORK_REPO'. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Release with tag '$TAG_NAME' does not exist in the fork '$FORK_REPO'. Proceeding."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge Upstream Tag
        if: steps.check_fork_release.outputs.skip == 'false'
        run: |
          DEFAULT_BRANCH=master # Using master as default branch
          git checkout $DEFAULT_BRANCH
          echo "Pulling latest changes from fork's origin $DEFAULT_BRANCH..."
          git pull origin $DEFAULT_BRANCH
          echo "Attempting to merge upstream tag ${{ steps.upstream_release.outputs.tag_name }} into $DEFAULT_BRANCH..."
          # Use the specific tag ref fetched from upstream
          git merge "refs/tags/${{ steps.upstream_release.outputs.tag_name }}" --no-ff -m "Merge upstream tag ${{ steps.upstream_release.outputs.tag_name }}" || {
            echo "Merge failed. Please resolve conflicts manually."
            exit 1
          }

      - name: Push Merge Commit
        if: steps.check_fork_release.outputs.skip == 'false'
        run: |
          DEFAULT_BRANCH=master # Using master as default branch
          echo "Pushing merge commit to origin/$DEFAULT_BRANCH..."
          git push origin $DEFAULT_BRANCH

      # --- Build Steps ---

      - uses: actions/setup-java@v4
        name: Setup Java
        if: steps.check_fork_release.outputs.skip == 'false'
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
        name: Setup Gradle
        if: steps.check_fork_release.outputs.skip == 'false'

      - name: Execute Gradle build
        if: steps.check_fork_release.outputs.skip == 'false'
        run: ./gradlew build

      # --- Debug Artifact Location ---
      - name: List build artifacts
        if: steps.check_fork_release.outputs.skip == 'false'
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing contents of build/:"
          ls -l build || echo "build directory not found."
          echo "Listing contents of build/libs:"
          ls -l build/libs || echo "build/libs directory not found or empty."
          echo "Listing all JAR files under build/:"
          find build -name '*.jar' || echo "No .jar files found under build/."

      # --- Create Release ---
      - name: Create Fork Release
        if: steps.check_fork_release.outputs.skip == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.upstream_release.outputs.tag_name }}
          name: ${{ steps.upstream_release.outputs.release_name }}
          body: ${{ steps.upstream_release.outputs.release_body }}
          prerelease: ${{ steps.upstream_release.outputs.is_prerelease == 'true' }}
          # Make sure this path is correct based on 'List build artifacts' output
          files: |
            build/libs/*.jar
          token: ${{ secrets.GH_PAT }} # Use PAT for release creation
