# .github/workflows/sync-upstream-release.yml

name: Sync Upstream Release and Build

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    # Runs every hour (adjust as needed)
    - cron: '0 * * * *'

jobs:
  sync_and_build:
    runs-on: ubuntu-latest # gh and jq are pre-installed here
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # 1. Checkout the fork repository
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 gets all history needed for merging
          fetch-depth: 0
          # PAT is needed to push merge commits and create releases
          token: ${{ secrets.GH_PAT }} # Ensure this secret exists in your fork

      # 2. Configure Git user for commits made by the action
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Add the upstream repository as a remote
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/JellyLabScripts/FarmHelper # Use HTTPS URL

      # 4. Get info about the LATEST release from UPSTREAM (tag, name, body, prerelease status)
      - name: Get Latest Upstream Release Info
        id: upstream_release
        env:
          # Use the built-in token for read-only API access to upstream
          GH_TOKEN: ${{ github.token }}
          UPSTREAM_REPO: JellyLabScripts/FarmHelper
        run: |
          # Use the robust script from section 4.4 above
          echo "Fetching latest release tag info from $UPSTREAM_REPO..."
          if ! latest_release_tag_json=$(gh release list --repo $UPSTREAM_REPO --limit 1 --json tagName); then
            echo "::error::Failed to run 'gh release list'."
            exit 1
          fi
          echo "Raw gh release list output: $latest_release_tag_json"
          if [[ -z "$latest_release_tag_json" || "$latest_release_tag_json" == "[]" ]]; then
            echo "No releases found on upstream repository $UPSTREAM_REPO."
            echo "No new release found. Exiting cleanly."
            exit 0
          fi
          tag_name=$(echo "$latest_release_tag_json" | jq -r '.[0].tagName')
          jq_exit_code=$?
          if [[ $jq_exit_code -ne 0 || -z "$tag_name" || "$tag_name" == "null" ]]; then
            echo "::error::Could not extract valid tag name from gh output. jq exit code: $jq_exit_code, extracted value: '$tag_name'"
            exit 1
          fi
          echo "Latest upstream tag found: $tag_name"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "Output 'tag_name' set to '$tag_name'"
          echo "Fetching details for tag $tag_name..."
          if ! release_details_json=$(gh release view "$tag_name" --repo $UPSTREAM_REPO --json isPrerelease,name,body); then
             echo "::error::Could not fetch details for release tag '$tag_name' using 'gh release view'."
             exit 1
          fi
          is_prerelease=$(echo "$release_details_json" | jq -r '.isPrerelease')
          release_name=$(echo "$release_details_json" | jq -r '.name')
          release_body=$(echo "$release_details_json" | jq -r '.body')
          echo "is_prerelease=$is_prerelease" >> $GITHUB_OUTPUT
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$release_body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Successfully retrieved and processed upstream release details."

      # 5. Check if a release with this EXACT tag already exists in THIS fork
      - name: Check if Release Exists in Fork for this Tag
        id: check_fork_release
        env:
          # Use PAT here in case fork is private, ensures permission
          GH_TOKEN: ${{ secrets.GH_PAT }}
          # github.repository is the name of the fork (e.g., YourName/FarmHelper)
          FORK_REPO: ${{ github.repository }}
          # Use the tag name retrieved in the previous step
          TAG_NAME: ${{ steps.upstream_release.outputs.tag_name }}
        run: |
          # Use the robust script from section 4.5 above
          echo "Checking for existing release with tag '$TAG_NAME' in fork repository '$FORK_REPO'..."
          if gh release view "$TAG_NAME" --repo "$FORK_REPO" > /dev/null 2>&1; then
            echo "Release with tag '$TAG_NAME' already exists in the fork '$FORK_REPO'. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Release with tag '$TAG_NAME' does not exist in the fork '$FORK_REPO'. Proceeding."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      # 6. Fetch ONLY the required tag and master branch from upstream (if needed)
      - name: Fetch Specific Upstream Tag and Master Branch
        if: steps.check_fork_release.outputs.skip == 'false'
        run: |
          # Use the robust script from section 4.8 above
          TARGET_TAG="${{ steps.upstream_release.outputs.tag_name }}"
          DEFAULT_BRANCH=master # Your default branch
          echo "Fetching specific tag '$TARGET_TAG' and branch '$DEFAULT_BRANCH' from upstream..."
          git fetch upstream "refs/tags/$TARGET_TAG:refs/tags/$TARGET_TAG" -v --progress --no-tags || { echo "Failed to fetch tag $TARGET_TAG"; exit 1; }
          git fetch upstream "$DEFAULT_BRANCH" -v --progress --no-tags || { echo "Failed to fetch branch $DEFAULT_BRANCH"; exit 1; }
          echo "Fetch commands finished successfully."
          echo "Verifying local tag '$TARGET_TAG' exists..."
          git tag -l "$TARGET_TAG" || { echo "Local tag '$TARGET_TAG' not found after fetch!"; exit 1; }
          echo "Local tag verified."

      # 7. Merge the fetched upstream tag into the fork's master branch (if needed)
      - name: Merge Upstream Tag
        if: steps.check_fork_release.outputs.skip == 'false'
        run: |
          DEFAULT_BRANCH=master # Your default branch
          TARGET_TAG="${{ steps.upstream_release.outputs.tag_name }}"
          git checkout $DEFAULT_BRANCH
          echo "Pulling latest changes from fork's origin $DEFAULT_BRANCH..."
          git pull origin $DEFAULT_BRANCH || { echo "Pull from origin failed"; exit 1; }
          echo "Attempting to merge upstream tag $TARGET_TAG into $DEFAULT_BRANCH..."
          git merge "refs/tags/$TARGET_TAG" --no-ff -m "Merge upstream tag $TARGET_TAG" || {
            echo "::error::Merge failed. Please resolve conflicts manually in the fork."
            exit 1
          }
          echo "Merge successful."

      # 8. Push the merge commit back to the fork's repository (if needed)
      - name: Push Merge Commit
        if: steps.check_fork_release.outputs.skip == 'false'
        run: |
          DEFAULT_BRANCH=master # Your default branch
          echo "Pushing merge commit to origin/$DEFAULT_BRANCH..."
          git push origin $DEFAULT_BRANCH

      # --- Build Steps (Run only if merge happened) ---

      # 9. Set up Java environment
      - uses: actions/setup-java@v4
        name: Setup Java
        if: steps.check_fork_release.outputs.skip == 'false'
        with:
          distribution: temurin
          java-version: 17

      # 10. Set up Gradle environment (Includes Caching)
      - uses: gradle/actions/setup-gradle@v3 # This action handles Gradle caching
        name: Setup Gradle
        if: steps.check_fork_release.outputs.skip == 'false'

      # 11. Execute the Gradle build command
      - name: Execute Gradle build
        if: steps.check_fork_release.outputs.skip == 'false'
        run: ./gradlew build

      # 12. List build artifacts (for verification)
      - name: List build artifacts
        if: steps.check_fork_release.outputs.skip == 'false'
        run: |
          echo "Listing contents of build/libs:"
          ls -l build/libs || echo "build/libs directory not found or empty."

      # 13. Create the release in the fork, mirroring upstream details (if needed)
      - name: Create Fork Release
        if: steps.check_fork_release.outputs.skip == 'false'
        uses: softprops/action-gh-release@v2
        with:
          # Use details retrieved from the upstream release
          tag_name: ${{ steps.upstream_release.outputs.tag_name }}
          name: ${{ steps.upstream_release.outputs.release_name }}
          body: ${{ steps.upstream_release.outputs.release_body }}
          prerelease: ${{ steps.upstream_release.outputs.is_prerelease == 'true' }}
          # Attach the built JAR file(s)
          files: |
            build/libs/*.jar
          # Use the PAT token to grant permission to create the release
          token: ${{ secrets.GH_PAT }}
